import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  container: { flex: 1 },
  screenContainer: { flex: 1 },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 20,
    marginTop: 15,
    marginBottom: 20,
  },
  headerTitle: { fontSize: 20, fontWeight: "700" },
  headerSubtitle: { fontSize: 12, fontWeight: "600", marginTop: 2 },

  courseCardWrapper: {
    width: 95,
    height: 110,
    borderRadius: 14,
    marginRight: 15,
    borderWidth: 2,
    padding: 2,
  },
  courseImage: { flex: 1, justifyContent: "flex-end" },
  courseOverlay: {
    backgroundColor: "rgba(0,0,0,0.3)",
    padding: 8,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  courseText: { color: "#FFFFFF", fontWeight: "700", fontSize: 10, lineHeight: 14 },

  sectionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 20,
    marginBottom: 15,
  },
  sectionTitle: { fontWeight: "800", fontSize: 18 },
  linkRow: { flexDirection: "row", alignItems: "center" },
  linkText: { fontWeight: "700", fontSize: 14, marginRight: 2 },

  classCard: {
    marginHorizontal: 20,
    padding: 18,
    borderRadius: 12,
    marginBottom: 25,
    borderWidth: 1,
    elevation: 2,
  },
  classTitle: { fontWeight: "800", fontSize: 16, marginBottom: 10 },
  classDetailsRow: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  classDetailItem: { flexDirection: "row", alignItems: "center", marginRight: 15 },
  classSubText: { fontSize: 12, marginLeft: 4, fontWeight: "500" },

  tabsContainer: { flexDirection: "row", marginHorizontal: 20, marginBottom: 10 },
  tabButton: { marginRight: 25, alignItems: "center", paddingBottom: 6 },
  tabText: { fontSize: 18, fontWeight: "500" },
  activeTabIndicator: {
    height: 3,
    width: "100%",
    position: "absolute",
    bottom: 0,
    borderRadius: 2,
  },

  contentWrapper: { paddingTop: 15, paddingBottom: 20, minHeight: 400 },
  newsCard: {
    marginHorizontal: 20,
    padding: 18,
    borderRadius: 12,
    marginBottom: 15,
    elevation: 2,
  },
  newsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  newsTitle: { fontWeight: "800", fontSize: 16 },
  badge: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: 12 },
  badgeText: { fontSize: 11, fontWeight: "700" },

  eventCard: {
    marginHorizontal: 20,
    borderRadius: 12,
    marginBottom: 15,
    flexDirection: "row",
    elevation: 2,
  },
  eventInfo: { flex: 1, padding: 16, justifyContent: "center" },
  eventTitle: {
    fontWeight: "700",
    fontSize: 15,
    marginBottom: 12,
    lineHeight: 20,
  },
  eventSubText: { fontSize: 12, marginBottom: 4, fontWeight: "500" },
  eventImage: { width: 110, borderTopRightRadius: 12, borderBottomRightRadius: 12 },

  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 20,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 20,
  },
  searchIcon: { marginRight: 10 },
  searchInput: { flex: 1, fontSize: 16 },
  coursesListWrapper: { paddingTop: 15, paddingBottom: 40, minHeight: "100%" },
  courseListItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 20,
    padding: 18,
    borderRadius: 12,
    marginBottom: 12,
    elevation: 2,
  },
  courseListTitle: { fontSize: 15, fontWeight: "700" },

  dateHeaderRow: { flexDirection: "row", alignItems: "center", marginHorizontal: 25, marginBottom: 25 },
  largeDateText: { fontSize: 44, fontWeight: "800", marginRight: 10 },
  monthYearCol: { justifyContent: "center" },
  monthText: { fontSize: 16, fontWeight: "600" },
  yearText: { fontSize: 16 },
  scheduleContentWrapper: {
    flex: 1,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingTop: 25,
  },
  daysRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 25,
    marginBottom: 30,
  },
  dayItem: { alignItems: "center", paddingVertical: 12, paddingHorizontal: 10, borderRadius: 12 },
  dayName: { fontSize: 13, marginBottom: 8, fontWeight: "600" },
  dayNumber: { fontSize: 16, fontWeight: "700" },
  dayTextActive: { color: "#FFFFFF" },
  timelineHeader: { flexDirection: "row", marginHorizontal: 25, marginBottom: 15 },
  timelineHeaderText: { fontSize: 16, fontWeight: "500" },
  timelineRow: { flexDirection: "row", paddingHorizontal: 25, marginBottom: 20 },
  timeColumn: { width: 50, alignItems: "center", paddingTop: 10 },
  startTimeText: { fontSize: 15, fontWeight: "700", marginBottom: 6 },
  endTimeText: { fontSize: 13, fontWeight: "500" },
  timelineDivider: { width: 1, marginHorizontal: 15, marginTop: 15, height: "80%" },
  scheduleCard: {
    flex: 1,
    borderRadius: 16,
    padding: 16,
    minHeight: 120,
    justifyContent: "space-between",
  },
  scheduleCardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  scheduleCardTitle: { fontSize: 16, fontWeight: "800", marginBottom: 4 },
  scheduleCardSubtitle: { fontSize: 12, fontWeight: "500" },
  scheduleCardBottom: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginTop: 15,
  },
  scheduleInfoRow: { flexDirection: "row", alignItems: "center", marginBottom: 4 },
  scheduleInfoText: { fontSize: 11, fontWeight: "500", marginLeft: 6 },

  chatContainer: { flex: 1 },
  chatListContent: { paddingHorizontal: 20, paddingTop: 15, paddingBottom: 20 },
  systemMessageContainer: {
    alignSelf: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    marginBottom: 15,
  },
  systemMessageText: { fontSize: 12, fontWeight: "500" },
  messageWrapper: { flexDirection: "row", marginBottom: 15, maxWidth: "80%" },
  messageWrapperMe: { alignSelf: "flex-end" },
  messageWrapperOther: { alignSelf: "flex-start" },
  avatarCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    alignSelf: "flex-end",
  },
  avatarText: { fontSize: 14, fontWeight: "700" },
  messageBubble: { padding: 12, borderRadius: 16, elevation: 1 },
  messageSender: { fontSize: 12, fontWeight: "700", marginBottom: 4 },
  messageText: { fontSize: 15, lineHeight: 22 },
  messageTime: { fontSize: 10, marginTop: 6, alignSelf: "flex-end" },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderTopWidth: 1,
  },
  attachButton: { padding: 5, marginRight: 5 },
  chatInput: {
    flex: 1,
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingTop: 10,
    paddingBottom: 10,
    fontSize: 15,
    maxHeight: 100,
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
  },

  profileHeaderBg: {
    paddingBottom: 60,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  profileTopNav: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 25,
    marginTop: 20,
  },
  headerTitleLight: { fontSize: 22, fontWeight: "800", color: "#FFFFFF" },
  profileCardPrimary: { alignItems: "center", marginTop: 20 },
  profileAvatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 4,
    borderColor: "#FFFFFF",
    marginBottom: 15,
  },
  profileInfoCore: { alignItems: "center" },
  profileName: { fontSize: 22, fontWeight: "800", color: "#FFFFFF", marginBottom: 4 },
  profileId: { fontSize: 14, color: "#D1FAE5", fontWeight: "600", marginBottom: 10 },
  roleBadge: {
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 10,
  },
  roleBadgeText: { color: "#FFFFFF", fontSize: 12, fontWeight: "700" },
  universityText: { color: "#D1FAE5", fontSize: 12, fontWeight: "500" },
  profileContentWrapper: { paddingHorizontal: 20, marginTop: -30 },
  statsBanner: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 15,
    borderRadius: 16,
    borderWidth: 1,
    elevation: 3,
    marginBottom: 20,
  },
  statBox: { alignItems: "center" },
  statValue: { fontSize: 18, fontWeight: "800", marginBottom: 4 },
  statLabel: { fontSize: 12, fontWeight: "500" },
  statDivider: { width: 1, height: "80%", alignSelf: "center" },
  premiumCard: {
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    elevation: 3,
    marginBottom: 20,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  cardTitle: { fontSize: 16, fontWeight: "800" },
  actionButton: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  actionButtonText: { color: "#FFFFFF", fontSize: 12, fontWeight: "700" },
  progressSection: { marginTop: 5 },
  progressRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  progressInfo: { flexDirection: "row", alignItems: "center" },
  dot: { width: 8, height: 8, borderRadius: 4, marginRight: 10 },
  progressText: { fontSize: 14, fontWeight: "500" },
  progressPercent: { fontSize: 14, fontWeight: "700" },
  staffPromptText: { fontSize: 14, lineHeight: 22 },
  menuItem: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 15 },
  menuItemLeft: { flexDirection: "row", alignItems: "center" },
  iconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  menuItemText: { fontSize: 15, fontWeight: "600" },

  settingsSectionTitle: { fontSize: 12, fontWeight: "800", marginBottom: 10, marginLeft: 5 },
  settingsCard: { borderRadius: 12, borderWidth: 1, paddingHorizontal: 15 },
  settingsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 15,
  },
  settingsLabelGroup: { flexDirection: "row", alignItems: "center" },
  settingsLabel: { fontSize: 15, fontWeight: "600", marginLeft: 12 },
  settingsDivider: { height: 1 },
  logoutButton: {
    marginTop: 40,
    backgroundColor: "#FEE2E2",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
  },
  logoutText: { color: "#EF4444", fontWeight: "700", fontSize: 16 },

  tabBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 25,
    paddingTop: 12,
    paddingBottom: 25,
    borderTopWidth: 1,
  },
  tabItem: { alignItems: "center" },
  tabLabel: { fontSize: 10, marginTop: 4 },
});